### ISSUE TITLE
activesupport 3.0.3

### ISSUE THREAD

**Issue by didlix** [OpenAMEE/amee-ruby#1]
Hello

Are there plans to add support for activesupport 3.0.3 / rails 3?

Kind Regards

didlix

**Comment by Floppy** [comment]
Hi,
We will hopefully be working on Rails 3 support in the near future, yes. Not sure exactly when, but sometime soon.

**Comment by didlix** [comment]
It seems to work quite well in its current state.

**Comment by Floppy** [comment]
Ah, that's promising! There isn't too much Rails-specific stuff in there at the moment (there is another gem for that), so as long as it doesn't use anything from activesupport that was deprecated, it should be OK.
